import type { RunResponseItem } from '@/contracts/AdapterRunnerGateway'
import type AdapterRunnerGateway from '@/contracts/AdapterRunnerGateway'
import type Adapter from '@/entities/Adapter'
import Drive from '@/facades/Drive'
import OpenAI from 'openai'

export default class implements AdapterRunnerGateway {
    public id = 'gpt-image-1'
    public name = 'GPT Image 1 Runner'
    public description = "A runner that uses OpenAI's API to process threads and items."

    constructor(
        private client: OpenAI,
        public adapter: Adapter
    ) {}

    public run: AdapterRunnerGateway['run'] = async (payload) => {
        // Implement the logic to interact with OpenAI's API
        // This is a placeholder implementation
        const { instructions } = payload

        const content: OpenAI.Responses.ResponseInputContent[] = []

        for (const instruction of instructions) {
            if (instruction.type === 'text') {
                content.push({
                    type: 'input_text',
                    text: instruction.data,
                })
            }
        }

        const response = await this.client.responses.create({
            model: 'gpt-4.1-mini',
            tools: [{ type: 'image_generation' }],
            input: [
                {
                    role: 'user',
                    content,
                },
            ],
        })

        const imageData = response.output
            .filter((output) => output.type === 'image_generation_call')
            .map((output) => output.result)

        const base64Image = imageData[0]

        if (!base64Image) {
            throw new Error('No image generated by OpenAI.')
        }

        const filename = createId() + '.png'
        const uint8 = $uint8.fromBase64(base64Image)

        const image = await Drive.write(filename, uint8)

        const result: RunResponseItem[] = []

        result.push({
            type: 'file',
            data: image,
        })

        return result
    }

    public async cleanup(): Promise<void> {
        // Optional cleanup logic if needed
    }
}
