import type { RunResponseItem } from '@/contracts/AdapterRunnerGateway'
import type AdapterRunnerGateway from '@/contracts/AdapterRunnerGateway'
import type Adapter from '@/entities/Adapter'
import Drive from '@/facades/Drive'
import FileMetaRepository from '@/facades/FileMetaRepository'
import OpenAI from 'openai'

export default class implements AdapterRunnerGateway {
    public id = 'gpt-image-1'
    public name = 'GPT Image 1 Runner'
    public description = "A runner that uses OpenAI's API to process threads and items."

    constructor(
        private client: OpenAI,
        public adapter: Adapter
    ) {}

    public findOrUploadFile = async (filename: string): Promise<string> => {
        const file = await Drive.find(filename)

        if (!file) {
            throw new Error(`File ${filename} not found.`)
        }

        const key = `openai:${this.adapter.id}:file-id`

        const meta = await FileMetaRepository.findOne({
            fileId: file.id,
            name: key,
        })

        if (meta) {
            return meta.value as string
        }

        const uint8 = await Drive.read(filename)

        if (!uint8) {
            throw new Error(`Failed to read file ${filename}.`)
        }

        const openaiFile = await this.client.files.create({
            file: $uint8.toFile(uint8, filename, file.mimetype),
            purpose: 'vision',
        })

        if (!openaiFile.id) {
            throw new Error(`Failed to upload file ${filename} to OpenAI.`)
        }

        await FileMetaRepository.create({
            fileId: file.id,
            name: key,
            value: openaiFile.id,
        })

        return openaiFile.id
    }

    public run: AdapterRunnerGateway['run'] = async (payload) => {
        // Implement the logic to interact with OpenAI's API
        // This is a placeholder implementation
        const { instructions } = payload

        const content: OpenAI.Responses.ResponseInputContent[] = []

        for (const instruction of instructions) {
            if (instruction.type === 'text') {
                content.push({
                    type: 'input_text',
                    text: instruction.data,
                })
                continue
            }

            if (instruction.type === 'image') {
                const uint8 = await Drive.read(instruction.data.filename)

                if (!uint8) {
                    throw new Error(`Image file ${instruction.data.filename} not found.`)
                }

                const fileId = await this.findOrUploadFile(instruction.data.filename)

                content.push({
                    type: 'input_image',
                    file_id: fileId,
                    detail: 'auto',
                })

                continue
            }
        }

        const response = await this.client.responses.create({
            model: 'gpt-4.1-mini',
            tools: [{ type: 'image_generation' }],
            input: [
                {
                    role: 'user',
                    content,
                },
            ],
        })

        const imageData = response.output
            .filter((output) => output.type === 'image_generation_call')
            .map((output) => output.result)

        const base64Image = imageData[0]

        if (!base64Image) {
            throw new Error('No image generated by OpenAI.')
        }

        const filename = createId() + '.png'
        const uint8 = $uint8.fromBase64(base64Image)

        const image = await Drive.write(filename, uint8)

        const result: RunResponseItem[] = []

        result.push({
            type: 'file',
            data: image,
        })

        return result
    }

    public async cleanup(): Promise<void> {
        // Optional cleanup logic if needed
    }
}
