name: Deploy

on:
    push:
      branches:
        - main

jobs:
    build:
        name: Build and Push to production
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build image
              run: docker build -t creative-draw:latest .

            - name: Save image
              run: docker save creative-draw:latest > creative-draw.tar

            - name: Upload image
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_KEY }}
                port: ${{ secrets.SSH_PORT }}
                source: creative-draw.tar 
                target: /home/${{ secrets.SSH_USER }}
                debug: true

            - name: Load image 
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: docker load -i /tmp/creative-draw.tar

            - name: restart docker compose
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  command_timeout: 10m
                  script: |
                      cd {{ secrets.DOCKER_COMPOSE_PATH }}
                      docker compose down
                      docker compose up --detach --wait --wait-timeout 120

            - name: Clean up 
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: rm -rf /tmp/creative-draw.tar

