name: Deploy

on:
    push:
      branches:
        - main

jobs:
    build:
        name: Build and Push to production
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build image
              run: docker build -t creative-draw:latest .

            - name: Upload image
              run: docker save creative-draw:latest | ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} docker load

            - name: restart docker compose
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.SSH_HOSTNAME }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  command_timeout: 10m
                  script: |
                      cd {{ secrets.DOCKER_COMPOSE_PATH }}
                      docker compose down
                      docker compose up --detach --wait --wait-timeout 120
