name: Deploy staging instance

on:
  push:
    branches:
      - develop

permissions:
  contents: write # allow GITHUB_TOKEN to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm' # enables automatic caching based on package-lock.json

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # built-in token, no manual secret needed
          publish_dir: ./dist
          publish_branch: build-staging

